apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-03-16T20:28:46Z'
  labels:
    app: testwebapp-docker
  name: testwebapp-docker
  namespace: testwebapp-docker
  resourceVersion: '125869'
  selfLink: /apis/build.openshift.io/v1/namespaces/myfirstweb/buildconfigs/testwebapp-docker
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'testwebapp-docker:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/ilanuk/testpython-docker.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'ubuntu:16.04'
    type: Docker
  triggers:
    - 
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: d543cfa5471b95c8
      type: Generic
    - github:
        secret: 3fec46245f4c9d99
      type: GitHub
status:
  lastVersion: 1
